title: Daphne Konstantinis Portfolio
logo:
  assets/IMG_4784 2.png
  assets/Grade Calculator.png
  assets/Inventory Manager.png
description: Final Project for CS106 - Making Sense of Data
show_downloads: true
theme: jekyll-theme-architect

