title: Daphne Konstantinis Portfolio
logo:
  assets/IMG_4784 2.png
  assets/Grade Calculator.png
  assets/Inventory Manager.png
description: text below image
show_downloads: true
theme: jekyll-theme-cayman

